name: shared
description: A new Flutter package project.
version: 0.0.4
homepage:
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  geoflutterfire_plus: ^0.0.29
  file_saver:
  core:
    path: ../core
    # git:
    #  url: https://github.com/Modern-IT-Solutions/core.git
    #  ref: arch2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  firebase_ui_firestore: ^1.6.4
  safe_device:
  device_info_plus: ^9.0.3
  screen_capture_event:
  flex_color_picker:
  # zplayer:
  #   path: ../zplayer
  # git:
  #  url: https://github.com/Modern-IT-Solutions/z-player.git
  #  ref: main
  image_picker:

  fast_rsa:
  convert:
  shared_preferences:
  url_launcher: ^6.1.14
  timeago:
  visibility_detector:
  photo_view:
  recase:
  # FluentIcons
  fluentui_system_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1


dependency_overrides:
  cloud_firestore: ^5.2.1

flutter:
