name: shared
description: A new Flutter package project.
version: 0.0.2
homepage:
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts:
  geoflutterfire2: ^2.3.15
  core:
    # path: /Users/mohamad/Desktop/projects/core
    git:
     url: https://github.com/Modern-IT-Solutions/core.git
     ref: main
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  firebase_ui_firestore: ^1.5.11
  safe_device:
  device_info_plus: ^9.0.3
  screen_capture_event:
  flex_color_picker: 
  zplayer:
    git:
      url: https://github.com/Modern-IT-Solutions/zplayer.git
      ref: main
  fast_rsa:
  convert:
  shared_preferences:
  url_launcher: ^6.1.14
  timeago:
  visibility_detector:
  photo_view:
  recase:
  # FluentIcons
  fluentui_system_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
